/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(rrcpulseshaping.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(f72dc3ca65819bea316b9d6a8a38bc33)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/rxprocessing_ecological/rrcpulseshaping.h>
// pydoc.h is automatically generated in the build directory
#include <rrcpulseshaping_pydoc.h>

void bind_rrcpulseshaping(py::module& m)
{

    using rrcpulseshaping    = gr::rxprocessing_ecological::rrcpulseshaping;


    py::class_<rrcpulseshaping, gr::block, gr::basic_block,
        std::shared_ptr<rrcpulseshaping>>(m, "rrcpulseshaping", D(rrcpulseshaping))

        .def(py::init(&rrcpulseshaping::make),
           D(rrcpulseshaping,make)
        )
        



        ;




}








