/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-rxprocessing_ecological
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_RXPROCESSING_ECOLOGICAL_API_H
#define INCLUDED_RXPROCESSING_ECOLOGICAL_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_rxprocessing_ecological_EXPORTS
#define RXPROCESSING_ECOLOGICAL_API __GR_ATTR_EXPORT
#else
#define RXPROCESSING_ECOLOGICAL_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_RXPROCESSING_ECOLOGICAL_API_H */
